#change user and host

[backend]
pangloss-api ansible_host=backend ansible_user=user

[frontend]
pangloss-mock-frontend ansible_host=frontend ansible_user=user

[all:vars]
ansible_python_interpreter=/usr/bin/python3
