#change user and host

[backend]
pangloss-api ansible_host=panglossbackend01.dhinfra.plus.ac.at ansible_user=root

[frontend]
pangloss-frontend ansible_host=panglossfrontend01.dhinfra.plus.ac.at ansible_user=root

[all:vars]
ansible_python_interpreter=/usr/bin/python3

